#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
    export TERM="xterm-256color"
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8

    source .powerlevelrc

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file

export VIRTUAL_ENV_DISABLE_PROMPT=1

if which jenv > /dev/null; then eval "$(jenv init -)"; fi

alias cat='bat'
alias makeitso='cd ~; brewu; cd Projects/scm_ensemble; pyenv activate scm_ensemble; ./scm_ensemble.py -u _; source deactivate; cd ~'
# virtualenv & an extra pyenv settings
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV="true"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"

#if [[ -r /usr/local/bin/virtualenvwrapper.sh ]]; then
#    source /usr/local/bin/virtualenvwrapper.sh
#else
#    echo "WARNING: Can't find virtualenvwrapper.sh"
#fi

export PYENV_ROOT="$HOME/.pyenv"
# export PATH=$PYENV_ROOT/bin:$PATH
#eval "$(pyenv init -)"
#eval "$(pyenv virtualenv-init -)"

export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-L/usr/local/opt/openssl/include"

export SCM_ENSEMBLE_PATH_TO_REPOSITORIES="~/Projects"
export PATH="$PATH:/usr/local/opt/mysql@5.6/bin"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
#[[ -f /Users/jgartland/Projects/webdriverio/packages/wdio-lambda-runner/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/jgartland/Projects/webdriverio/packages/wdio-lambda-runner/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
#[[ -f /Users/jgartland/Projects/webdriverio/packages/wdio-lambda-runner/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/jgartland/Projects/webdriverio/packages/wdio-lambda-runner/node_modules/tabtab/.completions/sls.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


